baseURL = "http://example.org/"
defaultContentLanguage = "en"
disqusShortname = "dream-plus"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en-us"
pygmentsCodeFences = true
pygmentsOptions = "linenos=table"
pygmentsUseClasses = true
theme = "dream-plus"
title = "MSPA Madden League Site"
[params]
author = "ML Productions"
avatar = "http://res.cloudinary.com/mspaleague/image/upload/g_north,l_mspa:website:CommishText,x_0,y_100/v1531001086/mspa/website/ChrisandCommish2.jpg"
bgBlur = "0px"
bgImage = "http://res.cloudinary.com/mspaleague/image/upload/v1518833237/mspa/misc/football_stadiumlights_bcgrd.jpg"
contentType = "post"
description = "MSPA CFM League Website"
enableCategories = true
enableColorBG = false
enableShareCard = true
enableTags = true
enableToc = true
favicon = "/img/defaultFav.ico"
itemsPerPage = 4
motto = "Where coaching dreams come true."
twitterEmoji = true
[social]
email = "moniqx4@gmail.com"
github = "moniqx4"
medium = ""
siteStartYear = 2018
stackoverflow = ""
twitter = "moniqx4"
